hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("ben", views.ben, name="ben"),
    path("becky", views.becky, name="becky"),
]

lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls'))
]

newyear/urls.py
from django.urls import path
from django.http import HttpRequest

from . import views

app_name = "newyear"

urlpatterns = [
    path("", views.index, name="index"),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def ben(request):
    return HttpResponse("Hello, Ben!")

def becky(request):
    return HttpResponse("Hello, Becky")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

newyear/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.day == 1 and now.month == 1
    })

tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value= 1, max_value= 5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
        
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Greet</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, JIMBOB</h1>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Hello</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %} 
            <h1>NO</h1>
        {% endif %} 
    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %} 

{% block body %}

    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">Submit
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %} 

{% block body %} 

    TASKS
    <ul>
        {% for item in tasks %} 
        <li>{{ item }}</li>
        {% empty %} 
        <li>No Tasks</li>
        {% endfor %} 
    </ul>
    <button type="button"><a href="{% url 'tasks:add' %}">Add Task</a></button>

{% endblock %} 

tasks/templates/tasks/layout.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %} 
        {% endblock %} 
    </body>
</html>